apiVersion: v1
kind: Service
metadata:
  name: {{.Values.deployment.name}}-service
  labels:
    app: {{.Values.deployment.name}}
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.deployment.name}}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 4900