{{- define "mylibcharts.secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
type: {{ .Values.secret.type | quote }}
stringData: {}
{{- end }}
{{- define "mylibcharts.secret" -}}
{{- include "mylibcharts.util.merge" (append . "mylibcharts.secret.tpl") -}}
{{- end -}}